<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Arquivo</title>
    <link href="vendor/twbs/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
</head>

<body>
    <div class="container">
        <h1 class="fs-1 text-center mb-5">Arquivos CSV</h1>
        <div class="mb-3">
            <form id="arquivo" enctype="multipart/form-data">
                <label for="formFile" class="form-label">Importar CSV</label>
                <input class="form-control" type="file" id="formFile" name="file">
                <button class="btn btn-primary mt-3" type="submit" value="Submit">Enviar</button>
            </form>
        </div>
        <div id="response"></div>
    </div>

    <script src="vendor/twbs/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        $(document).ready(function() {

            $('#arquivo').on('submit', function(e) {
                e.preventDefault();

                var formData = new FormData(this);

                $.ajax({
                    type: 'POST',
                    url: 'http://localhost/leituracsv/csv',
                    data: formData,
                    contentType: false,
                    processData: false,
                    dataType: 'json',
                    success: function(response) {

                        console.log("Resposta do servidor:", response);
                        if (response.mensagem) {
                            $('#response').html('<div class="alert alert-success">' + response.mensagem + '</div>');
                        } else if (response.erro) {
                            $('#response').html('<div class="alert alert-danger">' + response.erro + '</div>');
                        }
                    },
                    error(xhr, status, error) {
                        console.log("Status:", status);
                        console.log("Erro:", error);
                        console.log("Resposta:", xhr.responseText);
                    }

                })
            })
        })
    </script>

</body>

</html>